---
pool: 'Default'
trigger:
  - main
stages:
  - stage: terraform_init
    jobs:
      - job: terraform_init 
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'aws'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
            backendServiceAWS: 'aws'
            backendAWSBucketName: 'spc1811'
            backendAWSKey: 'terraform/terraform.tfstate'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'aws'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
            environmentServiceNameAWS: 'aws'