---
pool: 'Default'
trigger:
  - azuredevops
parameters:
  - name: s3_Bucket
    displayName: S3 Bucket
    type: string
    default: ansible1811
stages:
  - stage: install_ansible
    jobs:
      - job: install_ansible 
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'aws'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Ansible'
            backendServiceAWS: 'aws'
            backendAWSBucketName:  ${{ parameters.s3_Bucket }}
            backendAWSKey: 'terraform/terraform.tfstate'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'aws'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Ansible'
            environmentServiceNameAWS: 'aws'